export const DEFAULT_OPTIONS = {
  mode: "single",
  language: "zh-CN",
  timeout: 15000,
  retry: 2,
  preserveLinks: true,
  cleanLevel: "balanced",
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
};

export const IMAGE_COMPRESSION_RULES = {
  bookSizeLimit: 5 * 1024 * 1024,
  initialWidth: 1000,
  initialQuality: 60,
  minWidth: 400,
  minQuality: 20,
  widthStep: 100,
  qualityStep: 10,
};

export const TRACKING_QUERY_KEYS = new Set([
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "utm_id",
  "fbclid",
  "gclid",
  "igshid",
  "mc_cid",
  "mc_eid",
  "spm",
]);

export const ALLOWED_TAGS = [
  "article",
  "section",
  "div",
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "blockquote",
  "pre",
  "code",
  "table",
  "thead",
  "tbody",
  "tr",
  "th",
  "td",
  "figure",
  "figcaption",
  "img",
  "a",
  "strong",
  "em",
  "b",
  "i",
  "sup",
  "sub",
  "hr",
  "br",
  "span",
];

export const ALLOWED_ATTRIBUTES = {
  a: ["href", "title"],
  img: ["src", "alt", "title", "width", "height"],
  th: ["colspan", "rowspan"],
  td: ["colspan", "rowspan"],
  code: ["class"],
  pre: ["class"],
  span: ["class"],
  "*": [],
};
